name: Mark Stale Issues and PRs

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open for 30 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open for 30 days with no activity.'
          days-before-stale: 30
          days-before-close: 7
